// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNZhC4wV8JIhVrpS1h6_n2Jy4eZC68E9M',
    appId: '1:30282540322:web:8336c295ed66c5614ab17b',
    messagingSenderId: '30282540322',
    projectId: 'tubes-apb-120e9',
    authDomain: 'tubes-apb-120e9.firebaseapp.com',
    databaseURL: 'https://tubes-apb-120e9-default-rtdb.firebaseio.com',
    storageBucket: 'tubes-apb-120e9.appspot.com',
    measurementId: 'G-RX7909X9R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnftO6cEL_mpaCDkChHEUqzG8V5XQPcc4',
    appId: '1:30282540322:android:62c5f8eb1cb3ef504ab17b',
    messagingSenderId: '30282540322',
    projectId: 'tubes-apb-120e9',
    databaseURL: 'https://tubes-apb-120e9-default-rtdb.firebaseio.com',
    storageBucket: 'tubes-apb-120e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJNwtKVogUZLztj2KPTcRulcLnwS2miYM',
    appId: '1:30282540322:ios:c16b788aa7e00d214ab17b',
    messagingSenderId: '30282540322',
    projectId: 'tubes-apb-120e9',
    databaseURL: 'https://tubes-apb-120e9-default-rtdb.firebaseio.com',
    storageBucket: 'tubes-apb-120e9.appspot.com',
    iosClientId: '30282540322-1s15m9s1nqv9ihh8tg56ihoi02f0jvmk.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubesApp7',
  );
}
